caca_internals: export _caca_alloc2d
It is used by the image viewer:

/usr/bin/ld: img2txt-common-image.o: in function `load_image':
../../src/common-image.c:164: undefined reference to `_caca_alloc2d'

Fixes #59.